name: Make kernel bs patch for DSM 7.1+ for All Support Models

on:
  workflow_dispatch:
    inputs:
      dsm:
        description: 'Input DSM Version (ex: 7.1.0-42661-1)'
        required: true
        default: '7.1.0-42661'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Bulid
        id: bulid-bsp
        run: |
          patfile=${{github.event.inputs.dsm}}
          echo "::set-output name=patfile::$patfile"
          chmod +x ./.github/workflows/makeall.sh
          bash ./.github/workflows/makeall.sh ${{github.event.inputs.dsm}}

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: kernel bs patch for ${{ steps.bulid-bsp.outputs.patfile }}
          path: /opt/dist
